name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          extra_packages: "texlive-fonts-recommended texlive-latex-recommended texlive-latex-recommended-doc_ texlive-pictures-doc_ texlive-latex-base-doc_ texlive-pstricks-doc_ texlive-latex-extra texlive-latex-extra-doc_ texlive-fonts-recommended-doc_" 
